global:
  scrape_interval: 5s # 每 5 秒抓一次數據 (測試用設短一點，生產環境通常 15s 或 30s)

scrape_configs:
  - job_name: 'go_worker_pool'
    metrics_path: '/metrics'
    static_configs:
      # host.docker.internal 讓 Docker 容器可以訪問你本機跑的 Go 程式 (localhost:8080)
      - targets: ['host.docker.internal:8080']
  
  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']